blank_issues_enabled: true
contact_links:
  - name: 生活issue template
    about: 生活関連のタスクを管理するためのissue template
    url: https://github.com/idekworks/docusaurus/issues/new?title=生活タスク&template=life_template.md&projects=idekworks/2?labels=life&assignees=idekworks