blank_issues_enabled: true
contact_links:
  - name: 生活issue template
    about: 生活関連のタスクを管理するためのissue template
    url: https://github.com/idekworks/issues/new?template=life_template.md&projects=idekworks/2
